### ISSUE TITLE
Question about augment data

### ISSUE THREAD

**Issue by yhcao6** [meder411/PointNet-PyTorch#1]
In `augment_data` function in "dataloader.py", I notice after getting rotation matrix `Ry`, you directly multiply `Ry` and points to get rotated points like this: `vertices = Ry * vertices`

In my opinion, I think it should be `np.matmul(vertices, Ry)`

**Comment by meder411** [comment]
It was definitely wrong, but I believe it's `np.matmul(Ry, vertices)`. I made the fix
